apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook-civo
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: guestbook-civo-*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/hiddeco/kargo-civo.git
